### ISSUE TITLE
Consider dropping proc_macro_hygiene requirement

### ISSUE THREAD

**Issue by dtolnay** [nrc/proc-macro-rules#18]
If you find a way to make things work without label_break_value, then it's a small step to support the stable compiler by using [proc-macro-hack](https://github.com/dtolnay/proc-macro-hack).

<br>

```diff
diff --git a/Cargo.toml b/Cargo.toml
@@ -8,6 +8,7 @@
 license = "Apache-2.0/MIT"
 
 [dependencies]
+proc-macro-hack = "0.5"
 proc-macro-rules-macros = "0.1.0"
 proc-macro2 = "0.4.21"
 syn = { version = "0.15.0", features = ["full", "extra-traits"] }
```

```diff
diff --git a/src/lib.rs b/src/lib.rs
@@ -49,6 +49,8 @@
 extern crate syn;
 
 pub use crate::match_set::{Fork, MatchSet};
+
+#[proc_macro_hack::proc_macro_hack]
 pub use macros::rules;
 
 mod match_set;
```

```diff
diff --git a/macros/Cargo.toml b/macros/Cargo.toml
@@ -13,4 +13,5 @@
 [dependencies]
 quote = "0.6.0"
 syn = { version = "0.15.0", features = ["full", "extra-traits"] }
+proc-macro-hack = "0.5"
 proc-macro2 = "0.4.21"
```

```diff
diff --git a/macros/src/lib.rs b/macros/src/lib.rs
@@ -12,7 +12,7 @@
 crate mod expand;
 crate mod parse;
 
-#[proc_macro]
+#[proc_macro_hack::proc_macro_hack]
 pub fn rules(input: TokenStream) -> TokenStream {
     let rules: ast::Rules = syn::parse(input).expect("Parsing error");
     let result = expand::expand_rules(rules).into();
```

**Comment by nrc** [comment]
I don't think we can easily remove the use of labelled break (we can't use functions as the user might want to return, and I'm not aware of any other way to simulate the matching semantics, although surely there is some way). However, we might stabilise labelled break much quicker than proc macros in statement position, in which case we should definitely do this!

Thanks for the bug reports!

**Comment by dtolnay** [comment]
> I don't think we can easily remove the use of labelled break (we can't use functions as the user might want to return, and I'm not aware of any other way to simulate the matching semantics, although surely there is some way).

I opened #22 to remove labelled break.
