### ISSUE TITLE
Publish 0.3.0

### ISSUE THREAD

**Issue by mmastrac** [nrc/proc-macro-rules#31]
I've been looking for a crate like this for ages and I'd like to start using it for some experiments I'm running in Deno. The main version seems to be working well enough for the limited pattern matching we need in a certain subsystem and it replaces a ridiculously complex set of manual pattern-matching code.

Would you mind publishing a 0.3.0 version? A crate that isn't fully working is better than no crate and the older published versions are just too old to use.

**Comment by mmastrac** [comment]
Quick ping on this -- happy to help, and if needed be a temporary maintainer to assist with landing some of the patches.

**Comment by nrc** [comment]
Sorry for the delay! I've published 0.4.0 (I may have missed 0.3?)

**Comment by mmastrac** [comment]
Awesome! I will move our code over to the official crate. It's been extremely useful for our JS/Rust interface layer.
